실험1
hunlee1/MineSweeper pull request #4
Opened 2023-11-19 08:20 UTC by hunlee1

어떻게하는지 몰라서 일단 최대한 수정후 올립니다 .

2023-11-19 08:44 UTC, minsoowoo requested changes

2023-11-19 08:44 UTC, minsoowoo commented on src/landminehunting.java
> +        int boardSize = getInputInRange(scanner, "게임 보드 크기를 입력하세요 (5-15): ", 5, 15);
인자에 값을 직접 집어넣으면 읽기가 힘들어집니다. 두번째 인자 "게임 보드~"를 String 변수로 먼저 저장하고 변수를 인자로 넘기는 방식이 더 좋습니다.
5와 15같은 숫자는 final 변수로 변경해서 이름을 붙이고 이 상수화시킨 변수를 함수에 인자로 넘기는 방식으로 변경하는 것이 좋아 보이네요.

2023-11-19 08:44 UTC, minsoowoo commented on src/landminehunting.java
> +    private static int getInputInRange(Scanner scanner, String prompt, int min, int max) {
함수 인자가 4개나 되는데, 이것은 함수 호출 시나 함수 구조를 파악하기 힘들게 만듭니다. 인자 개수는 작을수록 좋아요.
scanner 변수는 인자로 넘겨줄 필요없이 landminehunting 클래스의 멤버 변수로 선언해주면 인자 없이 바로 사용할 수 있으니 그렇게 변경해주면 인자를 하나 줄일 수 있겠네요.
min, max 값은 실제 개수는 2개지만 한 세트로 봐도 무방하니까 prompt, min, max 값 3개를 인자로 가져도 됩니다.
하지만 더 좋은 방법은 min, max를 하나의 클래스로 선언해서 데이터를 해당 클래스의 객체에 넣고 객체만 인자로 넘기면 인자 개수를 더 줄일 수 있어 보이네요.
아니면 아예 prompt, min, max를 하나의 클래스에 데이터를 넣고 객체 하나만 넘기면 인자 하나로 줄일 수 있습니다.
어떤 방식을 채택하던지 지금보다 getInputInRange() 함수의 인자 개수를 더 줄여보세요.

2023-11-19 08:44 UTC, minsoowoo commented on src/landminehunting.java
> +public class landminehunting {
자바 클래스 이름을 만드는 방식에 적합한 이름으로 변경해 주는 것이 더 좋을 것 같네요.
첫 글자를 대문자로, 각 단어마다의 첫 글자도 대문자로 변경해서 LandMineHunting 클래스라는 이름을 추천합니다.

2023-11-19 08:44 UTC, minsoowoo commented on src/landminehunting.java
> +                (int) (boardSize * boardSize * 0.1), (int) (boardSize * boardSize * 0.2));
10번째 줄과 동일하게 인자를 정확하게 파악할 수 있도록 변수로 먼저 저장하고 변수를 넘기도록 변경하는 것이 가독성이 더 좋아질 것 같네요.

2023-11-19 08:44 UTC, minsoowoo commented on src/landminehunting.java
> +            Arrays.fill(row, 'O');
'O' 라는 글자가 어떤 의미인지 알 수 있도록 변수로 변경해서 의미있는 이름을 붙이고, 이 변수를 사용하도록 변경하는 것이 코드를 이해하기 더 좋아 보여요.

2023-11-19 08:44 UTC, minsoowoo commented on src/landminehunting.java
> +                board[x][y] = 'X';
41번째 줄의 'O'와 마찬가지로 'X'라는 값을 그대로 사용하는 것보다 의미가 있는 이름을 가진 변수로 변경해 주세요.

2023-11-19 08:44 UTC, minsoowoo commented on src/landminehunting.java
> +                if (board[i][j] == 'X') {
49-50번째 줄의 'X' 와 같은 의미로 사용된다면 'X'에 해당하는 변수를 전역변수로 선언해서 같이 사용하는 것이 좋을 것 같네요. 현재 상태로는 나중에 'X'의 값이 변경된다면 여러 곳에서 'X'의 값을 변경해 줘야 합니다.

2023-11-19 08:44 UTC, minsoowoo commented on src/landminehunting.java
> +                    System.out.print("X ");
"X " 라는 문자열이 어떤 의미인지 의미있는 이름을 가진 String 변수로 변경해서 사용하도록 변경해 주세요.

2023-11-19 08:44 UTC, minsoowoo commented on src/landminehunting.java
> +                    System.out.print(mineCount + " ");
"  "이라는 공백 문자열이 왜 사용되는지 의미있는 이름을 가진 변수로 변경해 주세요.

2023-11-19 08:44 UTC, minsoowoo commented on src/landminehunting.java
> +                if (isValidCell(i, j, size) && board[i][j] == 'X') {
'X'라는 값을 가진 의미있는 변수로 변경해 주세요. 위에서 사용된 'X'와 같은 의미라면 전역변수로 이미 선언된 변수를 사용하면 될 것 같네요.

2023-11-19 08:44 UTC, minsoowoo commented on src/landminehunting.java
> +        return x >= 0 && x < size && y >= 0 && y < size;
&& 연산이 여러번 반복되어서 가독성이 떨어지네요. && 연산을 각각 분리하는 것이 더 좋아 보여요.
```
if (x < 0)
    return false;

if (x >= size)
    return false;
...
...
return true;
```
이런 형태로 변경하는 것이 조건문을 보기 더 편할 것 같아요.

2023-11-19 13:26 UTC, hunlee1 commented
수정완료

2023-11-20 10:26 UTC, minsoowoo requested changes

2023-11-20 10:26 UTC, minsoowoo commented on src/LandMineHunting.java
> +        Range boardSizeRange = new Range("게임 보드 크기를 입력하세요 (" + MIN_BOARD_SIZE + "-" + MAX_BOARD_SIZE + "): ", MIN_BOARD_SIZE, MAX_BOARD_SIZE);
getInputInRange() 함수는 인자가 줄면서 깔끔해졌는데, 대신에 Range 객체를 만들 때 넘겨주는 인자가 보기 힘들어졌네요.
```
String InputBoardSizeMsg = "게임 보드 크기를 입력하세요 (" + MIN_BOARD_SIZE + "-" + MAX_BOARD_SIZE + "): ";
Range boardSizeRange = new Range(InputBoardSizeMsg,...)
```
이런 식으로 수정해서 최대한 가독성을 높여야 합니다. 현재 상태로는 어디까지가 첫번째 인자인지 구분하기가 힘드네요.

2023-11-20 10:26 UTC, minsoowoo commented on src/LandMineHunting.java
> +// 범위 데이터를 담는 클래스
이 주석은 필요없을거 같네요. 만약 부족하다면 Range라는 이름을 변경하는 것이 더 좋을 것 같네요.

2023-11-20 10:26 UTC, minsoowoo commented on src/LandMineHunting.java
> +class Range {
입력 범위를 저장하기 위한 클래스인데, 추가로 입력 메시지도 가지고 있죠. Range라는 이름만으로는 부족한 것 같네요.
InputRangeAndMsg 등으로 추가해서 좀 더 가지고 있는 데이터를 정확하게 표현해 주는 것이 좋을 것 같아요.

2023-11-20 10:26 UTC, minsoowoo commented on src/LandMineHunting.java
> +    // 상수화된 변수 추가
아래 변수들은 final 이나 대문자로 된 변수명으로 이미 충분히 상수 변수라는 것을 표현하고 있어요. 주석은 필요없겠네요.

2023-11-20 10:26 UTC, minsoowoo commented on src/LandMineHunting.java
> +    // Scanner를 멤버 변수로 변경
중복되는 주석이니까 삭제하는 것이 더 좋을 것 같아요.

2023-11-20 10:26 UTC, minsoowoo commented on src/LandMineHunting.java
> +        // 게임 보드 크기 입력 및 범위 확인
boardSizeRange 변수와 getInputInRange() 함수가 주석에 있는 내용을 충분히 알려주고 있습니다. 여기도 중복되는 주석이니 삭제하는 것이 더 좋겠네요.

2023-11-20 10:26 UTC, minsoowoo commented on src/LandMineHunting.java
> +        // 지뢰 개수 입력 및 범위 확인
이 주석도 중복되는 내용이니까 삭제하는 것이 더 좋을 것 같아요.

2023-11-20 10:26 UTC, minsoowoo commented on src/LandMineHunting.java
> +        int totalMines = getInputInRange(new Range("지뢰 개수를 입력하세요 (" + (int) (boardSize * boardSize * 0.1) + " ~ " + (int) (boardSize * boardSize * 0.2) + "): ",
31번째 줄과 동일하게 Range 객체 생성 시에 인자 구분이 힘드네요. String 변수를 따로 생성하고 Range 객체 생성 시에는 변수만 넘겨서 읽기 쉽게 변경하는 것이 좋습니다.

2023-11-20 10:26 UTC, minsoowoo commented on src/LandMineHunting.java
> +        // 게임 보드 생성
createGameBoard() 함수가 이미 이름으로 충분한 정보를 알려주고 있네요. 주석은 제거해 주세요.

2023-11-20 10:26 UTC, minsoowoo commented on src/LandMineHunting.java
> +        // 게임 보드 출력
이 주석도 필요 없을 것 같습니다.

2023-11-20 10:26 UTC, minsoowoo commented on src/LandMineHunting.java
> +    // Range 클래스를 인자로 받도록 수정
이 주석은 getInputRange() 함수의 동작을 제대로 설명하고 있지 못하네요. Range 객체를 인자로 받는 건 함수 정의 부분에서 바로 알 수 있으므로 중복되는 내용이기도 합니다. 주석은 삭제해 주세요.

2023-11-20 10:26 UTC, minsoowoo commented on src/LandMineHunting.java
> +        }
createGameBoard() 함수는 크게 두 가지 일을 하고 있네요. 게임 보드 초기화 작업과 지뢰 랜덤 배치 작업. 각각을 따로 함수로 만들면서 주석은 삭제하는 것이 좋습니다. 그러면 함수의 크기도 작게 만들 수 있죠. 게임 보드 초기화 작업을 하는 코드를 따로 함수로 만들면서 함수만 호출하도록 변경하는 것이 좋겠네요.

2023-11-20 10:26 UTC, minsoowoo commented on src/LandMineHunting.java
> +        while (totalMines > 0) {
지뢰 랜덤 배치 작업을 하는 코드도 따로 함수로 만들고 함수를 호출하도록 변경하는 것이 좋을 것 같아요.

2023-11-20 10:26 UTC, minsoowoo commented on src/LandMineHunting.java
> +                    System.out.print(MINE_SYMBOL + " ");
" " 이 공백 문자는 왜 들어가는 건가요? 의도를 알 수 있게 이름을 붙여서 변수로 변경하는 것이 좋을 것 같네요.

2023-11-20 10:26 UTC, minsoowoo commented on src/LandMineHunting.java
> +        return x >= 0 && x < size && y >= 0 && y < size;
&& 연산이 여러번 반복되어서 가독성이 떨어지네요. && 연산을 각각 분리하는 것이 더 좋아 보여요.
이전 리뷰에서 언급했는데 수정이 되어 있지 않네요.
countSurroundingMines() 함수가 변경되었는데 혹시 이해를 잘 못 한건가 싶어서 다시 설명합니다.
120 번째 줄의 
` return x >= 0 && x < size && y >= 0 && y < size; `
코드를 
```
if (x < 0)
    return false;
if (x >= size)
    return false;
if (y < 0)
    return false;
if (y >= size)
    return false;

return true;
```
이런 형태로 변경하는 것이 조건문을 보기 더 편할 것 같아요.

2023-11-21 08:47 UTC, minsoowoo requested changes

2023-11-21 08:47 UTC, minsoowoo commented on src/LandMineHunting.java
> +class InputRangeAndMsg {
min, max 값만 입력받는데 클래스 이름이 InputRangeAndMsg 로 되어 있네요. Msg 입력을 받지 않으니 클래스 이름을 변경해 주는 것이 더 좋아 보이네요.

2023-11-21 08:47 UTC, minsoowoo commented on src/LandMineHunting.java
> +    private static char[][] createAndInitializeGameBoard(int size) {
초기화 작업만 하는 함수인 것 같은데 createAndInitialize라고 하여 생성하고 초기화하는 작업을 동시에 하는 함수 이름으로 오해할 수 있을 것 같네요. 함수가 하는 일에 맞게 함수 이름을 변경해 줘야 할 것 같아요.

2023-11-21 09:51 UTC, minsoowoo approved these changes
수정된 거 확인했습니다. 수고했어요~

2023-11-21 09:51 UTC, merged